# Generated by Django 4.0.3 on 2023-02-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(db_column='Exercise_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('category', models.TextField(db_column='Category')),
                ('level', models.TextField(db_column='Level')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FutureWorkoutExercises',
            fields=[
                ('future_workout_ex_id', models.AutoField(db_column='Future_Workout_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
                ('position_in_list', models.IntegerField(db_column='Position_In_List')),
            ],
            options={
                'db_table': 'Future_Workout_Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('member_id', models.AutoField(db_column='Member_ID', primary_key=True, serialize=False)),
                ('email', models.TextField(db_column='Email')),
                ('password', models.TextField(db_column='Password')),
                ('phone_number', models.TextField(db_column='Phone_Number')),
                ('level_id', models.IntegerField(db_column='Level_ID')),
                ('birth_year', models.IntegerField(db_column='Birth_Year')),
                ('gender', models.TextField(db_column='Gender')),
                ('zipcode', models.IntegerField(db_column='Zipcode')),
            ],
            options={
                'db_table': 'Member_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriorWorkoutExercises',
            fields=[
                ('prior_workout_ex_id', models.AutoField(db_column='Prior_Workout_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
                ('actual_sets', models.IntegerField(blank=True, db_column='Actual_Sets', null=True)),
                ('actual_reps', models.IntegerField(blank=True, db_column='Actual_Reps', null=True)),
                ('position_in_list', models.IntegerField(db_column='Position_In_List')),
            ],
            options={
                'db_table': 'Prior_Workout_Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateExercises',
            fields=[
                ('template_ex_id', models.AutoField(db_column='Template_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
            ],
            options={
                'db_table': 'Template_Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateWorkout',
            fields=[
                ('template_id', models.AutoField(db_column='Template_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_cat', to='workout_api.exercise')),
                ('level', models.ForeignKey(db_column='Level', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_level', to='workout_api.exercise')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Template_Workout',
            },
        ),
        migrations.CreateModel(
            name='PriorWorkout',
            fields=[
                ('workout_id', models.AutoField(db_column='Workout_ID', primary_key=True, serialize=False)),
                ('when_completed', models.DateField(db_column='When_Completed')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_cat', to='workout_api.exercise')),
                ('level', models.ForeignKey(db_column='Level', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_level', to='workout_api.exercise')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Prior_Workout',
            },
        ),
        migrations.CreateModel(
            name='FutureWorkout',
            fields=[
                ('future_workout_id', models.AutoField(db_column='Future_Workout_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('perform_on', models.DateField(db_column='Perform_On')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_cat', to='workout_api.exercise')),
                ('level', models.ForeignKey(db_column='Level', on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_level', to='workout_api.exercise')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Future_Workout',
            },
        ),
    ]
