# Generated by Django 4.0.3 on 2023-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(db_column='Exercise_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('category', models.TextField(db_column='Category')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FutureWorkoutExercises',
            fields=[
                ('future_workout_ex_id', models.AutoField(db_column='Future_Workout_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
                ('position_in_list', models.IntegerField(db_column='Position_In_List')),
            ],
            options={
                'db_table': 'Future_Workout_Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriorWorkoutExercises',
            fields=[
                ('prior_workout_ex_id', models.AutoField(db_column='Prior_Workout_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
                ('position_in_list', models.IntegerField(db_column='Position_In_List')),
            ],
            options={
                'db_table': 'Prior_Workout_Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateExercises',
            fields=[
                ('template_ex_id', models.AutoField(db_column='Template_Ex_ID', primary_key=True, serialize=False)),
                ('target_sets', models.IntegerField(blank=True, db_column='Target_Sets', null=True)),
                ('target_reps', models.IntegerField(blank=True, db_column='Target_Reps', null=True)),
            ],
            options={
                'db_table': 'Template_Exercises',
                'managed': False,
            },
        ),
    ]
