# Generated by Django 4.0.3 on 2023-02-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(db_column='Level_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
            ],
            options={
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('member_id', models.AutoField(db_column='Member_ID', primary_key=True, serialize=False)),
                ('email', models.TextField(db_column='Email')),
                ('password', models.TextField(db_column='Password')),
                ('phone_number', models.TextField(db_column='Phone_Number')),
                ('birth_year', models.IntegerField(db_column='Birth_Year')),
                ('gender', models.TextField(db_column='Gender')),
                ('zipcode', models.IntegerField(db_column='Zipcode')),
                ('level_id', models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mem_level_id', to='workout_api.level')),
            ],
            options={
                'db_table': 'Member_account',
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='priorworkoutexercises',
            options={},
        ),
        migrations.CreateModel(
            name='TemplateWorkout',
            fields=[
                ('template_id', models.AutoField(db_column='Template_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_cat', to='workout_api.exercise')),
                ('level_id', models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_level_id', to='workout_api.level')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_mem', to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Template_Workout',
            },
        ),
        migrations.CreateModel(
            name='PriorWorkout',
            fields=[
                ('workout_id', models.AutoField(db_column='Workout_ID', primary_key=True, serialize=False)),
                ('when_completed', models.DateField(db_column='When_Completed')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_cat', to='workout_api.exercise')),
                ('level_id', models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_level_id', to='workout_api.level')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_mem', to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Prior_Workout',
            },
        ),
        migrations.CreateModel(
            name='FutureWorkout',
            fields=[
                ('future_workout_id', models.AutoField(db_column='Future_Workout_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('perform_on', models.DateField(db_column='Perform_On')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_cat', to='workout_api.exercise')),
                ('level_id', models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_level_id', to='workout_api.level')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_mem', to='workout_api.memberaccount')),
            ],
            options={
                'db_table': 'Future_Workout',
            },
        ),
    ]
