# Generated by Django 4.1.6 on 2023-02-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='level',
            table='Member_account',
        ),
        migrations.AlterModelTable(
            name='memberaccount',
            table=None,
        ),
    ]
