# Generated by Django 4.0.3 on 2023-02-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='futureworkout',
            name='level',
        ),
        migrations.RemoveField(
            model_name='priorworkout',
            name='level',
        ),
        migrations.RemoveField(
            model_name='templateworkout',
            name='level',
        ),
        migrations.AddField(
            model_name='futureworkout',
            name='level_id',
            field=models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='future_level_id', to='workout_api.memberaccount'),
        ),
        migrations.AddField(
            model_name='priorworkout',
            name='level_id',
            field=models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pri_level_id', to='workout_api.memberaccount'),
        ),
        migrations.AddField(
            model_name='templateworkout',
            name='level_id',
            field=models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_level_id', to='workout_api.memberaccount'),
        ),
    ]
