# Generated by Django 4.1.7 on 2023-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureworkout',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='priorworkout',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='templateworkout',
            name='category_id',
        ),
        migrations.AddField(
            model_name='futureworkout',
            name='category',
            field=models.TextField(db_column='Category', default='null'),
        ),
        migrations.AddField(
            model_name='priorworkout',
            name='category',
            field=models.TextField(db_column='Category', default='null'),
        ),
        migrations.AddField(
            model_name='templateworkout',
            name='category',
            field=models.TextField(db_column='Category', default='null'),
        ),
    ]
