# Generated by Django 4.1.6 on 2023-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0002_alter_level_table_alter_memberaccount_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.IntegerField(blank=True, db_column='Exercise_ID', primary_key=True, serialize=False),
        ),
    ]
