# Generated by Django 4.0.3 on 2023-02-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0002_level_memberaccount_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level_id',
            field=models.ForeignKey(db_column='Level_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_level_id', to='workout_api.level'),
        ),
        migrations.AddField(
            model_name='priorworkoutexercises',
            name='exercise_id',
            field=models.ForeignKey(db_column='Exercise_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.exercise'),
        ),
        migrations.AddField(
            model_name='priorworkoutexercises',
            name='workout',
            field=models.ForeignKey(db_column='Workout_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.priorworkout'),
            preserve_default=False,
        ),
    ]
