# Generated by Django 4.0.3 on 2023-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0003_alter_exercise_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureworkout',
            name='future_workout_id',
            field=models.IntegerField(blank=True, db_column='Future_Workout_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='futureworkoutexercise',
            name='future_workout_ex_id',
            field=models.IntegerField(blank=True, db_column='Future_Workout_Ex_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.IntegerField(blank=True, db_column='Level_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='member_id',
            field=models.IntegerField(blank=True, db_column='Member_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priorworkout',
            name='prior_workout_id',
            field=models.IntegerField(blank=True, db_column='Workout_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priorworkoutexercise',
            name='prior_workout_ex_id',
            field=models.IntegerField(blank=True, db_column='Prior_Workout_Ex_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='template_ex_id',
            field=models.IntegerField(blank=True, db_column='Template_Ex_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='templateworkout',
            name='template_id',
            field=models.IntegerField(blank=True, db_column='Template_ID', primary_key=True, serialize=False),
        ),
    ]
