# Generated by Django 4.0.3 on 2023-02-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0003_exercise_level_id_priorworkoutexercises_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorworkoutexercises',
            name='workout',
            field=models.ForeignKey(db_column='Workout_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workout_api.priorworkout'),
        ),
    ]
